DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    PSEUDONYM VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    USER_ID INT NOT NULL,
    PRODUCT_IMAGE_URL VARCHAR(255),
    PRICE DECIMAL(10,2) NOT NULL,
    PUBLIC TINYINT,
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);